### ISSUE TITLE
Django 1.9 deprecation warnings

### ISSUE THREAD

**Issue by Raekkeri** [funkybob/django-flatblocks#15]
Hi,
I'm working on a project that uses django-flatblocks and we recently updated to Django 1.8. I'm trying to get rid of all `RemovedInDjango19Warning` messages, and put together a pull request to silence one in flatblocks aswell: https://github.com/funkybob/django-flatblocks/pull/14

If you want me to change something in it, just give me a shout!

**Comment by funkybob** [comment]
Patch looks good... any other warnings, please open new tickets or a PR :)
