### ISSUE TITLE
Version on PyPi is 0.8, documentation is for version 0.9

### ISSUE THREAD

**Issue by Rembane** [funkybob/django-flatblocks#8]
Update the version on PyPi to version 0.9 so I can run `pip install django-flatblocks` and get the latest released version. It will also be easier to understand the documentation.

**Comment by krs-wraus** [comment]
Just wondering where we are on this.

**Comment by petebrowne** [comment]
When will this be pushed? I'm looking to get my app upgraded to Django 1.7, this is blocking.

**Comment by funkybob** [comment]
Have you been testing against git master?

Jenkins tests are currently failing against 1.4 and 1.7

If people are actively using this, and happy that it works, I'll fix the remaining issues and push a release.

**Comment by funkybob** [comment]
Since I fixed the tests to run in 1.7, and have tidied up the README, I've now pushed 0.9 to PyPi.

**Comment by petebrowne** [comment]
Thanks!
